export const userConstants = {
  ALL_USERS: "ALL_USERS",
  CU_Req: "CU_Req",
  CUSuc: "CU_SUC",
  CUErr: "CU_ERR",
  URErr: "UR_ERR",
  ULErr: "UL_ERR",
  UProfile: "U_PROFILE",
  UData: "U_DATA",
  UList: "U_LIST",
  UListDel: "U_LIST_DEL",
  UListUpt: "U_LIST_UPT",
  USER_SECURITY_QUESTIONS_REQ: "USER_SECURITY_QUESTIONS_REQ",
  USER_SECURITY_QUESTIONS: "USER_SECURITY_QUESTIONS",
  USER_SECURITY_QUESTION_ERR: "USER_SECURITY_QUESTION_ERR",
  MATCH_SECURITY_ANSWERS_REQ: "MATCH_SECURITY_ANSWERS_REQ",
  MATCH_SECURITY_ANSWERS: "MATCH_SECURITY_ANSWERS",
  MATCH_SECURITY_ANSWERS_ERR: "MATCH_SECURITY_ANSWERS_ERR",
  CAN_RESET_PASSWORD: "CAN_RESET_PASSWORD",
  PASSWORD_CHANGE_REQ: "PASSWORD_CHANGE_REQ",
  PASSWORD_CHANGE: "PASSWORD_CHANGE",
  PASSWORD_CHANGE_ERR: "PASSWORD_CHANGE_ERR",
  ALL_STUDENTS_REQ: "ALL_STUDENTS_REQ",
  ALL_STUDENTS: "ALL_STUDENTS",
  ALL_STUDENTS_ERR: "ALL_STUDENTS_ERR",
  ALL_TEACHERS_REQ: "ALL_TEACHERS_REQ",
  ALL_TEACHERS: "ALL_TEACHERS",
  ALL_TEACHERS_ERR: "ALL_TEACHERS_ERR",
  ACCOUNT_ENABLE_REQ: "ACCOUNT_ENABLE_REQ",
  ACCOUNT_ENABLE: "ACCOUNT_ENABLE",
  ACCOUNT_ENABLE_ERR: "ACCOUNT_ENABLE_ERR",
  UPDATE_COURSEACCESS_REQ: "UPDATE_COURSEACCESS_REQ",
  UPDATE_COURSEACCESS_ERR: "UPDATE_COURSEACCESS_ERR",
  UPDATE_COURSEACCESS: "UPDATE_COURSEACCESS",
  SEARCH_STUDENTS_REQ: "SEARCH_STUDENTS_REQ",
  SEARCH_STUDENTS_ERR: "SEARCH_STUDENTS_ERR",
  SEARCH_STUDENTS: "SEARCH_STUDENTS",
  ALL_ADMINS: "ALL_ADMINS",
  ALL_ADMINS_REQ: "ALL_ADMINS_REQ",
  ALL_ADMINS_ERR: "ALL_ADMINS_ERR",
  CLEAR_NOTIFICATION_REQ: "CLEAR_NOTIFICATION_REQ",
  CLEAR_NOTIFICATION_ERR: "CLEAR_NOTIFICATION_ERR",
  SELECTED_NOTIFICATION: "SELECTED_NOTIFICATION",

  COMPLETED_LESSONS_REQ: "COMPLETED_LESSONS_REQ",
  COMPLETED_LESSONS_ERR: "COMPLETED_LESSONS_ERR",
  COMPLETED_LESSONS: "COMPLETED_LESSONS",
};

export const snackBarConstants = {
  ShowSnack: "SHOW_SNACK",
  HideSnack: "HIDE_SNACK",
};

export const contactUsPageTextConstants = {
  // get
  CONTACT_US_PAGE_TEXT: "CONTACT_US_PAGE_TEXT",
  CONTACT_US_PAGE_TEXT_REQ: "CONTACT_US_PAGE_TEXT_REQ",
  CONTACT_US_PAGE_TEXT_ERR: "CONTACT_US_PAGE_TEXT_ERR",
  // edit
  CONTACT_US_PAGE_TEXT_EDIT: "CONTACT_US_PAGE_TEXT_EDIT",
  CONTACT_US_PAGE_TEXT_EDIT_REQ: "CONTACT_US_PAGE_TEXT_EDIT_REQ",
  CONTACT_US_PAGE_TEXT_EDIT_ERR: "CONTACT_US_PAGE_TEXT_EDIT_ERR",
};

export const aboutUsConstants = {
  // get
  ABOUT_US: "ABOUT_US",
  ABOUT_US_REQ: "ABOUT_US_REQ",
  ABOUT_US_ERR: "ABOUT_US_ERR",
  // edit
  ABOUT_US_EDIT: "ABOUT_US_EDIT",
  ABOUT_US_EDIT_REQ: "ABOUT_US_EDIT_REQ",
  ABOUT_US_EDIT_ERR: "ABOUT_US_EDIT_ERR",
};

export const contactUsConstants = {
  // SEND MESSAGE
  CONTACT_US_FORM_SEND_MESSAGE_REQ: "CONTACT_US_FORM_SEND_MESSAGE_REQ",
  CONTACT_US_FORM_SEND_MESSAGE_ERR: "CONTACT_US_FORM_SEND_MESSAGE_ERR",
  CONTACT_US_FORM_SEND_MESSAGE: "CONTACT_US_FORM_SEND_MESSAGE",
};

export const messageConstants = {
  CLEAR_MESSAGE_NOTIFICATION: "CLEAR_MESSAGE_NOTIFICATION",
  MESSAGE_NOTIFICATION: "MESSAGE_NOTIFICATION",
};

export const navBarConstants = { SETCount: "SET_COUNT" };
